services:
  attendance-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
    env_file:
      - .env
    volumes:
      - attendance_data:/app/data

volumes:
  attendance_data:
    driver: local
